### PR TITLE
Adding article on moving a Cloud Foundry...

### PR DESCRIPTION
**Pull request by timirnich**
... hello world app to Kubernetes.

### CODE REVIEW

**Review by CbranSUSE — APPROVED** [review]

**Review by agracey — APPROVED** [review]
This is good. I think the only think I might add is ingress if you wanted? By explicitly stating you are using k3s, you get an ingress controller for free and don't need to explain that part.

**Comment by timirnich** [comment]
> This is good. I think the only think I might add is ingress if you wanted? By explicitly stating you are using k3s, you get an ingress controller for free and don't need to explain that part.

I didn't use Traefik in my experiment, hence didn't explain it here. But you're right, it makes the narrative fall slightly short compared to the CF experience with random routes and stuff. Let me dig into this a bit and maybe we can have a brief chat about this later today.

**Comment by timirnich** [comment]
@agracey have a look at the latest commit. I've expanded a bit on services and ingress.

**Review by agracey — APPROVED** [review]
I like it!

**Pull request merged**
